### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by samdraz** [keplerproject/luafilesystem#22]
everytime when i'm trying to install 
```c:\lua\lua52.dll : fatal error LNK1107```
shows up

**Comment by bonez001** [comment]
where can I find lua5.3.lib?

**Comment by soapdog** [comment]
This is still happening on Windows 10 with Lua 5.2.

```

c:\Users\soapdog\prog\lua\luarocks-2.4.0-win32>luarocks install luafilesystem
Installing https://luarocks.org/luafilesystem-1.6.3-2.src.rock
cl /nologo /MD /O2 -c -Fosrc/lfs.obj -IC:/lua/include src/lfs.c
lfs.c
link -dll -def:lfs.def -out:lfs.dll C:/lua/lua52.dll src/lfs.obj
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\lua\lua52.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x330

Error: Build error: Failed compiling module lfs.dll
```

**Comment by hishamhm** [comment]
@soapdog  Do you have c:\lua\lua52.lib in your system?

Try editing your LuaRocks config file and change the value of LUALIB to point to the lua52.lib file.

LuaRocks will tell the location of your config file if you type `luarocks` with no arguments.

**Comment by soapdog** [comment]
@hishamhm I don't have it. I have lua52.dll and liblua52.a. My lua prebuilt binaries came from luabinaries project. They are not shipping lua52.lib on their windows download. Should the lib point to a DLL on windows? Also, thanks for the quick reply, I moved this to #82 because this issue is closed here.
